"use client";

import { CustomerAnalysisData } from "@/lib/types/financial-bi";
import {
  BarChart, Bar, ComposedChart, Line, XAxis, YAxis, Tooltip,
  ResponsiveContainer, CartesianGrid, Legend,
} from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

interface CustomerAnalysisTabProps { data: CustomerAnalysisData; }

const segmentColors = ["#22c55e", "#f59e0b", "#ef4444"];

function formatK(value: number): string {
  return value >= 1000 ? `$${(value / 1000).toFixed(1)}k` : `$${value.toFixed(0)}`;
}

function compactCustomerName(value: string) {
  return value.length > 22 ? `${value.slice(0, 22)}…` : value;
}

export function CustomerAnalysisTab({ data }: CustomerAnalysisTabProps) {
  const activeSegment = data.segments.find((segment) => segment.segment === "Active");
  const totalCustomers = data.segments.reduce((sum, segment) => sum + segment.count, 0);
  const totalSegmentRevenue = data.segments.reduce((sum, segment) => sum + segment.revenue, 0);
  const top3Share = data.concentration[Math.min(2, data.concentration.length - 1)]?.cumulativePct || 0;
  const top10Share = data.concentration[Math.min(9, data.concentration.length - 1)]?.cumulativePct || 0;
  const activeRevenueShare = totalSegmentRevenue > 0 && activeSegment
    ? (activeSegment.revenue / totalSegmentRevenue) * 100
    : 0;
  const avgActiveRevenue = activeSegment && activeSegment.count > 0
    ? activeSegment.revenue / activeSegment.count
    : 0;

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <div className="rounded-lg border bg-white p-3">
          <div className="text-[10px] uppercase tracking-wide text-gray-500">Active customers</div>
          <div className="mt-1 text-2xl font-extrabold text-gray-900">{activeSegment?.count || 0}</div>
          <div className="text-xs text-gray-500">{totalCustomers > 0 ? `${((activeSegment?.count || 0) / totalCustomers * 100).toFixed(1)}% of tracked base` : "No active base"}</div>
        </div>
        <div className="rounded-lg border bg-white p-3">
          <div className="text-[10px] uppercase tracking-wide text-gray-500">Active revenue share</div>
          <div className="mt-1 text-2xl font-extrabold text-brand-verde">{activeRevenueShare.toFixed(1)}%</div>
          <div className="text-xs text-gray-500">{formatK(activeSegment?.revenue || 0)} generated by active accounts</div>
        </div>
        <div className="rounded-lg border bg-white p-3">
          <div className="text-[10px] uppercase tracking-wide text-gray-500">Top 10 concentration</div>
          <div className="mt-1 text-2xl font-extrabold text-amber-600">{top10Share.toFixed(1)}%</div>
          <div className="text-xs text-gray-500">Top 3 already represent {top3Share.toFixed(1)}% of revenue</div>
        </div>
        <div className="rounded-lg border bg-white p-3">
          <div className="text-[10px] uppercase tracking-wide text-gray-500">Median customer value</div>
          <div className="mt-1 text-2xl font-extrabold text-gray-900">{formatK(data.ltv.median)}</div>
          <div className="text-xs text-gray-500">Average active account {formatK(avgActiveRevenue)}</div>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
      <Card>
        <CardHeader>
          <CardTitle className="text-sm">Revenue Concentration</CardTitle>
          <p className="text-xs text-gray-500">Pareto view of the customers that explain most of the selected-window revenue.</p>
        </CardHeader>
        <CardContent>
          <ResponsiveContainer width="100%" height={250}>
            <ComposedChart data={data.concentration.slice(0, 12)}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
              <XAxis dataKey="customer" tickFormatter={compactCustomerName} tick={{ fontSize: 9 }} angle={-30} textAnchor="end" height={52} />
              <YAxis yAxisId="rev" tickFormatter={formatK} tick={{ fontSize: 11 }} />
              <YAxis yAxisId="pct" orientation="right" tickFormatter={(v) => `${v.toFixed(0)}%`} tick={{ fontSize: 11 }} domain={[0, 100]} />
              <Tooltip formatter={(value: number, name: string) => name === "Cumulative %" ? [`${value.toFixed(1)}%`, name] : [formatK(value), name]} />
              <Legend />
              <Bar yAxisId="rev" dataKey="revenue" name="Revenue" fill="var(--brand-tangerina)" radius={[4, 4, 0, 0]} />
              <Line yAxisId="pct" type="monotone" dataKey="cumulativePct" name="Cumulative %" stroke="#8b5cf6" strokeWidth={2} dot={false} />
            </ComposedChart>
          </ResponsiveContainer>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle className="text-sm">Top 10 Customers by Revenue</CardTitle>
          <p className="text-xs text-gray-500">Use this list to validate concentration, renewals and account ownership.</p>
        </CardHeader>
        <CardContent>
          <ResponsiveContainer width="100%" height={250}>
            <BarChart data={data.topCustomers} layout="vertical">
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
              <XAxis type="number" tickFormatter={formatK} tick={{ fontSize: 11 }} />
              <YAxis type="category" dataKey="customer" tickFormatter={compactCustomerName} tick={{ fontSize: 10 }} width={140} />
              <Tooltip formatter={(v: number) => formatK(v)} />
              <Bar dataKey="totalPaid" fill="var(--brand-verde)" radius={[0, 4, 4, 0]} />
            </BarChart>
          </ResponsiveContainer>
          <div className="mt-4 space-y-2">
            {data.topCustomers.slice(0, 5).map((customer, index) => (
              <div key={customer.customer} className="flex items-center justify-between rounded-lg border bg-gray-50 px-3 py-2 text-sm">
                <div className="min-w-0">
                  <div className="font-semibold text-gray-900">{index + 1}. {customer.customer}</div>
                  <div className="text-xs text-gray-500">Top account in the selected window</div>
                </div>
                <div className="font-bold text-gray-900">{formatK(customer.totalPaid)}</div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle className="text-sm">Customer Segments</CardTitle>
          <p className="text-xs text-gray-500">Status split based on recent invoice activity and the revenue attached to each group.</p>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {data.segments.map((segment, index) => {
              const countPct = totalCustomers > 0 ? (segment.count / totalCustomers) * 100 : 0;
              const revenuePct = totalSegmentRevenue > 0 ? (segment.revenue / totalSegmentRevenue) * 100 : 0;
              return (
                <div key={segment.segment} className="rounded-lg border bg-gray-50 p-3">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <span className="inline-block h-2.5 w-2.5 rounded-full" style={{ backgroundColor: segmentColors[index] || "#94a3b8" }} />
                      <span className="font-semibold text-gray-900">{segment.segment}</span>
                    </div>
                    <span className="text-sm font-bold text-gray-900">{segment.count}</span>
                  </div>
                  <div className="mt-2 flex items-center justify-between text-xs text-gray-500">
                    <span>{countPct.toFixed(1)}% of customers</span>
                    <span>{formatK(segment.revenue)} revenue</span>
                    <span>{revenuePct.toFixed(1)}% of revenue</span>
                  </div>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle className="text-sm">Customer Value Benchmarks</CardTitle>
          <p className="text-xs text-gray-500">Median is the cleaner operational number; average shows how much large accounts skew the base.</p>
        </CardHeader>
        <CardContent className="space-y-3 py-4">
          <div className="rounded-lg border bg-white p-4 text-center">
            <div className="text-[10px] uppercase tracking-wide text-gray-500">Average LTV</div>
            <div className="mt-1 text-3xl font-extrabold text-brand-verde">{formatK(data.ltv.average)}</div>
          </div>
          <div className="rounded-lg border bg-gray-50 p-4 text-center">
            <div className="text-[10px] uppercase tracking-wide text-gray-500">Median LTV</div>
            <div className="mt-1 text-2xl font-bold text-gray-900">{formatK(data.ltv.median)}</div>
          </div>
          <div className="rounded-lg border bg-amber-50 p-3 text-xs text-amber-800">
            Average active customer revenue in the selected window is {formatK(avgActiveRevenue)}. Compare this against the top-10 concentration before assigning portfolio risk.
          </div>
        </CardContent>
      </Card>
      </div>
    </div>
  );
}
