// ---------------------------------------------------------------------------
// A1 Level Questions — Section 1
// Topics: to be, simple present (3rd person -s), articles (a/an/the),
//         there is/are, personal pronouns, basic prepositions, imperatives
//         Vocabulary: workplace vocab, greetings, numbers, daily life
// Context: career/immigration themes for Brazilian immigrants in the US
// ---------------------------------------------------------------------------

import { BankQuestion } from './types';

export const A1_QUESTIONS: BankQuestion[] = [
  // --- Adapted from original Section 1 questions ---
  {
    id: 'a1_gram_01',
    level: 'A1',
    section: 1,
    skillType: 'grammar',
    question: 'Choose the correct form: "She _____ a software engineer at a company in Miami."',
    options: ['am', 'is', 'are', 'be'],
    correctIndex: 1,
  },
  {
    id: 'a1_vocab_01_resume',
    level: 'A1',
    section: 1,
    skillType: 'vocabulary',
    question: 'What does "resume" mean in a job-search context?',
    options: [
      'To start again',
      'A document listing your work experience and education',
      'A type of interview',
      'A job offer letter',
    ],
    correctIndex: 1,
  },
  {
    id: 'a1_gram_02',
    level: 'A1',
    section: 1,
    skillType: 'grammar',
    question: 'Complete: "I _____ looking for a new job in the United States."',
    options: ['is', 'am', 'are', 'be'],
    correctIndex: 1,
  },
  {
    id: 'a1_gram_03',
    level: 'A1',
    section: 1,
    skillType: 'grammar',
    question: 'Which sentence is correct?',
    options: [
      'He work every day in the office.',
      'He works every day in the office.',
      'He working every day in the office.',
      'He to work every day in the office.',
    ],
    correctIndex: 1,
  },
  {
    id: 'a1_gram_04',
    level: 'A1',
    section: 1,
    skillType: 'grammar',
    question: 'What is the correct question form? "_____ you speak English at work?"',
    options: ['Does', 'Do', 'Is', 'Are'],
    correctIndex: 1,
  },

  // --- New A1 questions ---
  {
    id: 'a1_gram_05',
    level: 'A1',
    section: 1,
    skillType: 'grammar',
    question: '"There _____ three offices on the second floor."',
    options: ['is', 'are', 'has', 'have'],
    correctIndex: 1,
  },
  {
    id: 'a1_gram_06',
    level: 'A1',
    section: 1,
    skillType: 'grammar',
    question: '"_____ name is Maria and _____ is from Brazil."',
    options: ['Her / she', 'She / her', 'Her / her', 'She / she'],
    correctIndex: 0,
  },
  {
    id: 'a1_vocab_02',
    level: 'A1',
    section: 1,
    skillType: 'vocabulary',
    question: 'Which word means "a person who hires you for a job"?',
    options: ['Employee', 'Employer', 'Customer', 'Colleague'],
    correctIndex: 1,
  },
  {
    id: 'a1_vocab_03',
    level: 'A1',
    section: 1,
    skillType: 'vocabulary',
    question: 'Your boss says "Can you send me the report?" What is "the report"?',
    options: ['A summary document', 'A phone call', 'A meeting', 'An email address'],
    correctIndex: 0,
  },
  {
    id: 'a1_gram_07',
    level: 'A1',
    section: 1,
    skillType: 'grammar',
    question: '"_____ quiet during the meeting, please."',
    options: ['Be', 'Is', 'Are', 'Been'],
    correctIndex: 0,
  },
  {
    id: 'a1_gram_08',
    level: 'A1',
    section: 1,
    skillType: 'grammar',
    question: '"I always _____ lunch at 12 PM."',
    options: ['has', 'have', 'having', 'am have'],
    correctIndex: 1,
  },
  {
    id: 'a1_vocab_04',
    level: 'A1',
    section: 1,
    skillType: 'vocabulary',
    question: 'What does "deadline" mean?',
    options: [
      'The end of a line',
      'The last day to complete a task',
      'A type of employment',
      'A salary increase',
    ],
    correctIndex: 1,
  },
  {
    id: 'a1_gram_09',
    level: 'A1',
    section: 1,
    skillType: 'grammar',
    question: 'Choose the correct article: "I need _____ umbrella for today."',
    options: ['a', 'an', 'the', 'no article needed'],
    correctIndex: 1,
  },
  {
    id: 'a1_gram_10',
    level: 'A1',
    section: 1,
    skillType: 'grammar',
    question: '"The meeting is _____ Tuesday _____ 3 PM."',
    options: ['in / at', 'on / at', 'at / on', 'on / in'],
    correctIndex: 1,
  },
  {
    id: 'a1_vocab_05',
    level: 'A1',
    section: 1,
    skillType: 'vocabulary',
    question: 'What does "colleague" mean?',
    options: ['A person you study with', 'A person you work with', 'A person who manages you', 'A person who teaches you'],
    correctIndex: 1,
  },
  {
    id: 'a1_gram_11',
    level: 'A1',
    section: 1,
    skillType: 'grammar',
    question: '"_____ there a cafeteria in your building?"',
    options: ['Are', 'Is', 'Has', 'Have'],
    correctIndex: 1,
  },
  {
    id: 'a1_vocab_06',
    level: 'A1',
    section: 1,
    skillType: 'vocabulary',
    question: 'A new employee says "Nice to meet you." What is the most natural reply?',
    options: [
      'I am fine, thank you.',
      'Nice to meet you too.',
      'Yes, I work here.',
      'Good morning.',
    ],
    correctIndex: 1,
  },
];
