// ---------------------------------------------------------------------------
// A2 Level Questions — Section 2
// Topics: past simple, comparatives/superlatives, going to/will,
//         first conditional, much/many, present perfect (intro), phrasal verbs
//         Vocabulary: common expressions, false cognates (PT-BR), workplace routines
// Context: career/immigration themes for Brazilian immigrants in the US
// ---------------------------------------------------------------------------

import { BankQuestion } from './types';

export const A2_QUESTIONS: BankQuestion[] = [
  // --- Adapted from original Section 2 questions ---
  {
    id: 'a2_gram_01',
    level: 'A2',
    section: 2,
    skillType: 'grammar',
    question: 'Choose the correct past tense: "I _____ to the United States in 2019."',
    options: ['move', 'moved', 'moving', 'have move'],
    correctIndex: 1,
  },
  {
    id: 'a2_gram_02',
    level: 'A2',
    section: 2,
    skillType: 'grammar',
    question: 'Fill in the blank: "The meeting is _____ Monday _____ 9 a.m."',
    options: ['in / at', 'on / at', 'at / on', 'on / in'],
    correctIndex: 1,
  },
  {
    id: 'a2_vocab_01',
    level: 'A2',
    section: 2,
    skillType: 'vocabulary',
    question: "Your coworker says \"How's it going?\" on Monday morning. What is the most natural reply?",
    options: [
      'I am going to the office.',
      'It goes well, thank you.',
      'Not bad, how about you?',
      'Yes, it is going.',
    ],
    correctIndex: 2,
  },
  {
    id: 'a2_gram_03',
    level: 'A2',
    section: 2,
    skillType: 'grammar',
    question: 'Choose the correct sentence about a past event:',
    options: [
      'Yesterday I have finished the report.',
      'Yesterday I finished the report.',
      'Yesterday I was finish the report.',
      'Yesterday I did finished the report.',
    ],
    correctIndex: 1,
  },
  {
    id: 'a2_vocab_02',
    level: 'A2',
    section: 2,
    skillType: 'vocabulary',
    question: '"Actually" in English means:',
    options: [
      'Currently / at this moment (atualmente)',
      'In fact / really (na verdade)',
      'Exactly (exatamente)',
      'Obviously (obviamente)',
    ],
    correctIndex: 1,
  },

  // --- New A2 questions ---
  {
    id: 'a2_gram_04',
    level: 'A2',
    section: 2,
    skillType: 'grammar',
    question: '"She _____ her resume to ten companies last week."',
    options: ['send', 'sent', 'sended', 'has sent'],
    correctIndex: 1,
  },
  {
    id: 'a2_gram_05',
    level: 'A2',
    section: 2,
    skillType: 'grammar',
    question: '"This office is _____ than the old one."',
    options: ['more big', 'biggest', 'bigger', 'most big'],
    correctIndex: 2,
  },
  {
    id: 'a2_gram_06',
    level: 'A2',
    section: 2,
    skillType: 'grammar',
    question: '"If it _____ tomorrow, I will drive to work."',
    options: ['rains', 'will rain', 'rained', 'rain'],
    correctIndex: 0,
  },
  {
    id: 'a2_vocab_03',
    level: 'A2',
    section: 2,
    skillType: 'vocabulary',
    question: 'Your supervisor asks, "Can you cover my shift on Friday?" What does "cover my shift" mean?',
    options: [
      'To work in place of someone else',
      'To shorten the shift',
      'To report the shift to HR',
      'To arrive late for the shift',
    ],
    correctIndex: 0,
    explanation: 'To cover a shift means to work that scheduled time for another person.',
  },
  {
    id: 'a2_vocab_04',
    level: 'A2',
    section: 2,
    skillType: 'vocabulary',
    question: '"I need to _____ up early tomorrow for my shift."',
    options: ['get', 'take', 'put', 'come'],
    correctIndex: 0,
  },
  {
    id: 'a2_gram_07',
    level: 'A2',
    section: 2,
    skillType: 'grammar',
    question: '"How _____ experience do you have in customer service?"',
    options: ['many', 'much', 'lots', 'few'],
    correctIndex: 1,
  },
  {
    id: 'a2_gram_08',
    level: 'A2',
    section: 2,
    skillType: 'grammar',
    question: '"I have _____ finished my first week at the new job."',
    options: ['yet', 'already', 'since', 'for'],
    correctIndex: 1,
  },
  {
    id: 'a2_gram_09',
    level: 'A2',
    section: 2,
    skillType: 'grammar',
    question: '"I am _____ to apply for the supervisor position next month."',
    options: ['go', 'going', 'gone', 'went'],
    correctIndex: 1,
  },
  {
    id: 'a2_vocab_05',
    level: 'A2',
    section: 2,
    skillType: 'vocabulary',
    question: 'A recruiter writes, "I\'ll follow up next week." What does "follow up" mean here?',
    options: [
      'To contact you again after this conversation',
      'To hire you immediately',
      'To cancel the process',
      'To ask you to work overtime',
    ],
    correctIndex: 0,
    explanation: 'To follow up means to contact someone again after a previous message or meeting.',
  },
  {
    id: 'a2_gram_10',
    level: 'A2',
    section: 2,
    skillType: 'grammar',
    question: 'Which sentence uses the comparative correctly?',
    options: [
      'My new job is more good than my old one.',
      'My new job is gooder than my old one.',
      'My new job is better than my old one.',
      'My new job is the best than my old one.',
    ],
    correctIndex: 2,
  },
  {
    id: 'a2_vocab_06',
    level: 'A2',
    section: 2,
    skillType: 'vocabulary',
    question: 'What does "overtime" mean at work?',
    options: [
      'When work is too difficult',
      'Extra hours worked beyond your normal schedule',
      'A work break',
      'The time you arrive at work',
    ],
    correctIndex: 1,
  },
  {
    id: 'a2_gram_11',
    level: 'A2',
    section: 2,
    skillType: 'grammar',
    question: '"She _____ to the US two years ago and _____ here since then."',
    options: ['moved / lives', 'moved / has lived', 'has moved / lives', 'moves / has lived'],
    correctIndex: 1,
  },
  {
    id: 'a2_vocab_07',
    level: 'A2',
    section: 2,
    skillType: 'vocabulary',
    question: '"Please log in to the portal before the training starts." What does "log in" mean?',
    options: [
      'Sign into the system with your account',
      'Leave the building',
      'Print the training schedule',
      'Record work hours on paper',
    ],
    correctIndex: 0,
    explanation: 'To log in means to access a digital system using your account credentials.',
  },
  {
    id: 'a2_gram_12',
    level: 'A2',
    section: 2,
    skillType: 'grammar',
    question: '"There are _____ options available, but not _____."',
    options: ['many / much', 'much / many', 'a few / many', 'lots / few'],
    correctIndex: 0,
  },
  {
    id: 'a2_vocab_08',
    level: 'A2',
    section: 2,
    skillType: 'vocabulary',
    question: 'Which phrase means "to stop working at a job"?',
    options: [
      'To be hired',
      'To quit',
      'To get promoted',
      'To clock in',
    ],
    correctIndex: 1,
  },
  {
    id: 'a2_gram_13',
    level: 'A2',
    section: 2,
    skillType: 'grammar',
    question: '"I _____ the manager if I _____ you."',
    options: ['will call / were', "would call / were", "would call / was", "will call / was"],
    correctIndex: 1,
    explanation: 'This uses the second conditional: "I would call" + "if I were you."',
  },
  {
    id: 'a2_vocab_09',
    level: 'A2',
    section: 2,
    skillType: 'vocabulary',
    question: 'What does "to fill out a form" mean?',
    options: [
      'To throw away a form',
      'To complete the information in a form',
      'To create a new form',
      'To read a form quickly',
    ],
    correctIndex: 1,
  },
];
